name: my continaer Hello world
author: Yuzhe Liu
description: Some descriptions
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: YuzheL
Outputs:
  time:
    description: "The greeting time"
runs:
  using: "docker"
  image: "Dockerfile"
  # entrypoint:
  args:
    - ${{ inputs.who-to-greet }}
  # env: 
