name: My Second CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-actions-job:
    runs-on: ubuntu-latest
    steps:
      - name: List Files before checkout my repo
        run: |
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY 
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Checkout my repo
        uses: actions/checkout@v2
      - name: List Files after checkout my repo
        run: |
          pwd
          ls -la

      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with: 
          who-to-greet: LYZ
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
