name: my JS Hello world
author: Yuzhe Liu
description: Some descriptions
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Yuzhe
Outputs:
  time:
    description: "The greeting time"
runs:
  using: "node12"
  main: "index.js"
