name: My Own Docker CI 

on:
  push:
    branches: [ testBats ]
    # branches: [ main ]
  pull_request:
    branches: [ testBats ]
    # branches: [ main ]

jobs:
  run-bash-job:
    runs-on: ubuntu-latest
    steps:
      - name: my first step - echoing
        run: echo "I am about to run command from within container using my own iamge!"

      - name: List Files before checkout my repo
        run: |
          echo "pwd:"
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY 
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          echo "/ dir:"
          ls -la /

      - name: check out my repo
        uses: actions/checkout@v2

      - name: List Files after checkout my repo
        run: |
          echo "pwd:"
          pwd
          ls -la
          echo "/ dir:"
          ls -la /

      - name: my real run docker container with dynamic module
        # run: ./.github/actions/hello-docker/build.sh 1.21.1 ngx_mirror
        run: |
          cp -r ./src/DynamicModule/* ./.github/actions/hello-docker/
          cd ./.github/actions/hello-docker/
          ./build.sh 1.21.1 ngx_mirror
          ./docker-build.sh 1.21.1 ngx_mirror
        # with:
        #   who-to-greet: "MyTestingWorldLALALALALALAL"
        # should use my actio.yml in hello-docker and pass 1.21.1 ./ngx_mirror as env in action.yml
