name: build Nginx with dynamic module CI 

on:
  push:
    branches: [ cleanup_br ]
  pull_request:
    branches: [ cleanup_br ]

jobs:
  run-bash-job:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout repo
        run: |
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY 
          echo $GITHUB_WORKSPACE
          ls -la /
      - name: Check out repo
        uses: actions/checkout@v2
      - name: List files after checkout repo
        run: |
          pwd
          ls -la
          ls -la /
      - name: Build and run docker container
        run: ./.github/actions/dynamic-module-docker/build.sh 1.21.1 ngx_mirror

