name: build Nginx with dynamic module CI 

on:
  push:
    branches: [ testBatsCleanup ]
  pull_request:
    branches: [ testBatsCleanup ]

jobs:
  build-nginx-with-dynamic-module-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1    
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install bats submodules from git for testing support
        run: |
          git submodule add https://github.com/bats-core/bats-support.git test/DynamicModule/test_helper/bats-support
          git submodule add https://github.com/bats-core/bats-assert.git test/DynamicModule/test_helper/bats-assert
          git submodule add https://github.com/bats-core/bats-file.git test/DynamicModule/test_helper/bats-file
      - name: Unit Test
        run: |
          bats ./test/DynamicModule
      - name: Build and run docker container
        run: |
          cp -r ./src/DynamicModule/* ./.github/actions/dynamic-module-docker/
          cd ./.github/actions/dynamic-module-docker/
          ./build.sh $nginxVersion ngx_mirror
          ./docker-build.sh $nginxVersion ngx_mirror
        env:
          nginxVersion: 1.21.1