name: "Bats tests CI"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  run_bats_tests:
    name: run bats test cases
    runs-on: ubuntu-latest
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out my repo
        uses: actions/checkout@v2

      - name: Test
        run: bats -r .