name: "Bats tests CI"
on:
  push:
    branches: [ testBats ]
  pull_request:
    branches: [ testBats ]


jobs:
  run_bats_tests:
    name: run bats test cases
    runs-on: ubuntu-latest
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out my repo
        uses: actions/checkout@v2

      - name: install bats module for testing from git
        run: |
          pwd
          ls -la
          echo "ls -la tests/* :"
          ls -la tests/*
          git submodule add https://github.com/bats-core/bats-support.git test/test_helper/bats-support
          git submodule add https://github.com/bats-core/bats-assert.git test/test_helper/bats-assert
          git submodule add https://github.com/bats-core/bats-file.git test/test_helper/bats-file
          ls -la .git/modules/*
          ls -la tests/*

      - name: Test
        run: bats ./tests/test1.bats