name: My First CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-bash-job:
    runs-on: ubuntu-latest
    steps:
      - name: my first step - echoing
        run: eccho "This is an echo testing!!!"
      - name: my second step
        run: |
          node -v
          npm -v
